#!/bin/sh
sudo pacman -Syu
sudo pacman -S xorg nvidia
git clone https://github.com/urbankatern/dotfiles
git clone https://gitlab.com/dwt1/wallpapers
yay -S dmscripts-git
sudo pacman -S sddm i3 dmenu rofi picom nitrogen pcmanfm firefox pandoc
cp ~/dotfiles/.config/*.* ~/.config/
sudo systemctl enable sddm
echo "now restart"
