#!/bin/sh
sudo pacman -Syu
sudo pacman -S --no-confirm xorg nvidia
git clone https://gitlab.com/dwt1/wallpapers
yay -S dmscripts-git
sudo pacman -S --no-confirm sddm i3 dmenu rofi picom nitrogen pcmanfm firefox pandoc trayer
cp ~/dotfiles/.config/ ~
sudo systemctl enable sddm
echo "now restart"
