font_family JetBrainsMono Nerd Font Mono
font_size 13

disable_ligatures yes
enable_audio_bell no

shell zsh

remember_window_size no
window_padding_width 5

background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

sync_to_monitor no
include ./theme.conf

